services:
  mysql:
    image: mysql:8-oracle
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: user1234
      MYSQL_DATABASE: todos
      MYSQL_USER: digitalskies
      MYSQL_PASSWORD: user1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todos
      SPRING_DATASOURCE_USERNAME: digitalskies
      SPRING_DATASOURCE_PASSWORD: user1234
    depends_on:
      mysql:
        condition: service_healthy