spring.application.name=Demo
#spring.profiles.active = dev
logging.level.com.digitalskies.demo = debug

currency-service.url = https://wwww.defaulturl.com
currency-service.username = default_username
currency-service.key = default_key
management.endpoints.web.exposure.include = health,metrics
server.port=8080
# view resolvers
spring.mvc.view.prefix = /WEB-INF/jsp/
spring.mvc.view.suffix = .jsp
spring.mvc.format.date = yyyy-MM-dd

spring.security.user.password=test

#spring.datasource.url =jdbc:h2:mem:testdb
#spring.h2.console.enabled=true

# PostgreSQL DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/todos
spring.datasource.username=digitalskies
spring.datasource.password=user1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
# allow spring boot to create tables
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.defer-datasource-initialization=false
#spring.sql.init.mode=never
#spring.sql.init.continue-on-error=false

spring.flyway.enabled=true
logging.level.org.flywaydb=debug
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true

jwt.secret=${JWT_SECRET_KEY_BASE64}