CREATE TABLE "users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    hashed_password VARCHAR(255)
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    hashed_token VARCHAR(255),
    created_at BIGINT,
    expires_at BIGINT
);

ALTER TABLE notes ADD COLUMN owner_id VARCHAR(255);

